CREATE TABLE balances (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    insert_time timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    version int,
    json jsonb NOT NULL
);

CREATE INDEX balances__insert_time_idx ON balances USING btree (insert_time);
CREATE INDEX balances__market_id_exchange_id_idx ON balances USING btree (((json #>> '{market_id, exchange_id}')::text));
CREATE INDEX balances__market_id_currency_pair_idx ON balances USING btree (((json #>> '{market_id, currency_pair}')::text));
CREATE INDEX balances__balance_creation_time_idx ON balances USING btree (((json ->> 'balance_creation_time')::text));
