CREATE TABLE metrics_events (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    insert_time timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    version int,
    json jsonb NOT NULL
);

CREATE INDEX metrics_events__measure_time_idx ON metrics_events USING btree (((json ->> 'measure_time')::text));
CREATE INDEX metrics_events__event_type_idx ON metrics_events USING btree (((json ->> 'event_type')::text));

insert into public.cleanup_settings (table_name, period, column_name)
values ('metrics_events', '1 mons', 'insert_time');