CREATE TABLE liquidation_prices (
     id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
     insert_time timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
     version int,
     json jsonb NOT NULL
 );

CREATE INDEX liquidation_prices__insert_time_idx ON liquidation_prices USING btree (insert_time);
