CREATE TABLE prices_sources (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    insert_time timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    version int,
    json jsonb NOT NULL
);

CREATE INDEX prices_sources__insert_time_idx ON prices_sources USING btree (insert_time);
