CREATE TABLE disposition_explanations (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    insert_time timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    version int,
    json jsonb NOT NULL
);

CREATE INDEX disposition_explanations__insert_time_idx ON disposition_explanations USING btree (insert_time);
