CREATE TABLE transactions (
    id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    insert_time timestamp WITH TIME ZONE NOT NULL DEFAULT now(),
    version int,
    json jsonb NOT NULL
);

CREATE INDEX transactions__insert_time_idx ON transactions USING btree (insert_time);
CREATE INDEX transactions__market_id_exchange_id_idx ON transactions USING btree (((json #>> '{market_id, exchange_id}')::text));
CREATE INDEX transactions__market_id_currency_pair_idx ON transactions USING btree (((json #>> '{market_id, currency_pair}')::text));
CREATE INDEX transactions__transaction_creation_time_idx ON transactions USING btree (((json ->> 'transaction_creation_time')::text));