[strategy]
spread = 1000
currency_pair = { base = "btc", quote = "usdt" }
max_amount = 3
exchange_account_id = "Binance_0"

[[core.exchanges]]
exchange_account_id = "Binance_0"
is_margin_trading = false
request_trades = false
websocket_channels = ["depth20@100ms", "trade"]
subscribe_to_market_data = true

currency_pairs = [
    { base = "eth", quote = "btc"  },
    { base = "eos", quote = "btc"  },
    { base = "btc", quote = "usdt"  }
]
